module.exports={LoginLink:'/html[1]/body[1]/div[1]/header[1]/div[2]/div[1]/div[1]/div[3]/div[1]/ul[1]/li[1]/a[1]',
emailID:'//div[@class=\'group\']//input[@id=\'email\']', 
password:'//div[@class=\'group\']//input[@id=\'pass\']',
loginClick:'//button[@id=\'send2\']//span[contains(text(),\'Log In\')]', 
homeap:'//span[contains(text(),\'Home Appliances\')]',
viewprod:'//a[@class=\'btn\']',
iron:'//a[@class=\'product-item-link\'][contains(text(),\'1000W Dry Iron - Ezio 06\')]',
cart:'//span[contains(text(),\'Add to sCart\')]',
submail:'//input[@id=\'newsletter\']',
subbtn:'//button[@class=\'action subscribe primary\']',
};